[build]
    command = "yarn build"
    publish = "build"
[[plugins]]
	package = "netlify-plugin-cache-nextjs"
    	[plugins.inputs]
    		custom_build_dir_name = "build"
[[plugins]]
    package = "@netlify/plugin-nextjs"